### ISSUE TITLE
VS Code autocomplete fails in JSX

### ISSUE THREAD

**Issue by mike-kasianov** [melange-re/melange-for-react-devs#49]
Hi,
First of all great thanks for a such cool resource.
I'm making my very first steps in ReasonML and OCaml and for me it seems very useful.

I'm stuck with VS Code setup problem. It does not provide autocomplete for JSX HTML tags. As for me the reason may be due to errors I provide in the screenshot below.
![Screenshot 2024-06-24 at 16 19 20](https://github.com/melange-re/melange-for-react-devs/assets/2269723/cc36e685-1317-4ca7-af1e-5e4b013c88d7)

Seems it can't find `Js.t`.
![Screenshot 2024-06-24 at 16 21 59](https://github.com/melange-re/melange-for-react-devs/assets/2269723/c6c5ce6f-b10d-46de-b6ec-e92f1ee470c3)

Please add instruction how to manage this problem.

**Comment by mike-kasianov** [comment]
This template https://github.com/melange-re/melange-opam-template does not have such problem.
Autocomplete for HTML tags works as expected.

**Comment by feihong** [comment]
@mike-kasianov Does `npm run build` succeed? What is its output?

**Comment by feihong** [comment]
Probably not related, but this PR reverting back to OCaml 5.1.1. was just merged today. Maybe you can try pulling again and reinstalling the opam switch?

**Comment by mike-kasianov** [comment]
I have no problem with building so `npm run build` works good.
The only problem is VS code can't build things for it's internal usage. I guess the reason might be in VSCode OCaml Platform setup.
Just open `src/counter/Index.re` and try to jump to the `ReactDOM.Client.render` function

**Comment by jchavarri** [comment]
From what I understand, the goal is to navigate the opam installed packages the same way that the application sources are handled (cmd-click, see types, not see a bunch of "unbound module" errors...)

This is a larger problem than Melange, as it happens for any OCaml project, including those using "native OCaml", see https://github.com/ocamllabs/vscode-ocaml-platform/issues/624.

**Comment by jchavarri** [comment]
I don't think there's much we can do in the melange book, besides waiting for the issue to be fixed upstream or waiting until Dune integrates the package management handling.
